  MODULE('IKAPP001.CLW')
BrowseUcenik           PROCEDURE                      !Browse the Ucenik file
BrowsePredmet_odjava   PROCEDURE                      !Browse the Predmet_odjava file
BrowseOdjava           PROCEDURE                      !Browse the Odjava file
BrowseStavka_odjave    PROCEDURE                      !Browse the Stavka_odjave file
BrowsePredmet_prijava  PROCEDURE                      !Browse the Predmet_prijava file
BrowsePromjena         PROCEDURE                      !Browse the Promjena file
BrowseStavka_promjene  PROCEDURE                      !Browse the Stavka_promjene file
BrowseIzostanak        PROCEDURE                      !Browse the Izostanak file
BrowseIspitni_rok      PROCEDURE                      !Browse the Ispitni_rok file
  END
