  MODULE('IKAPP003.CLW')
SelectVrsta_promjene_ispita PROCEDURE                 !Select a Vrsta_promjene_ispita Record
UpdatePromjena         PROCEDURE                      !Form Promjena
SelectPromjena         PROCEDURE                      !Select a Promjena Record
SelectPredmet_prijava  PROCEDURE                      !Select a Predmet_prijava Record
UpdateStavka_promjene  PROCEDURE                      !Form Stavka_promjene
SelectIspitni_rok      PROCEDURE                      !Select a Ispitni_rok Record
SelectRazlog_izostanka PROCEDURE                      !Select a Razlog_izostanka Record
UpdateIzostanak        PROCEDURE                      !Form Izostanak
UpdateIspitni_rok      PROCEDURE                      !Form Ispitni_rok
UpdateRazlog_izostanka PROCEDURE                      !Form Razlog_izostanka
  END
