  MODULE('IKAPP002.CLW')
BrowseRazlog_izostanka PROCEDURE                      !Browse the Razlog_izostanka file
BrowseVrsta_promjene_ispita PROCEDURE                 !Browse the Vrsta_promjene_ispita file
UpdateUcenik           PROCEDURE                      !Form Ucenik
UpdatePredmet_odjava   PROCEDURE                      !Form Predmet_odjava
SelectUcenik           PROCEDURE                      !Select a Ucenik Record
UpdateOdjava           PROCEDURE                      !Form Odjava
SelectOdjava           PROCEDURE                      !Select a Odjava Record
SelectPredmet_odjava   PROCEDURE                      !Select a Predmet_odjava Record
UpdateStavka_odjave    PROCEDURE                      !Form Stavka_odjave
UpdatePredmet_prijava  PROCEDURE                      !Form Predmet_prijava
  END
